- src/actions.js
- src/components/ContributionPlanForm.js
- src/dialogs/CreateContributionPlanBundleDetailsDialog.js
- src/dialogs/UpdateContributionPlanBundleDetailsDialog.js
- src/index.js
- src/pickers/ContributionPlanPicker.js
- src/reducer.js
Introduces changes required for implementing https://openimis.atlassian.net/browse/OFS-190 - published picker for Contribution Plan and changed its behavior so that it can be reused in Contract module.
> OFS-190: Publish ContributionPlanPicker

- src/actions.js
- src/components/ContributionPlanForm.js
- src/components/ContributionPlanSearcher.js
TICKET: [OFS-112](https://openimis.atlassian.net/browse/OFS-112)
> OFS-112: Fixed Contribution Plan form and Contribution Plan picker

- README.md
- src/index.js
TICKET: [OFS-238](https://openimis.atlassian.net/browse/OFS-238)
> OFS-238: Added CP and CBP contribution for Admin menu entry

- README.md
- src/actions.js
- src/components/ContributionPlanForm.js
- src/components/ContributionPlanHeadPanel.js
- src/components/ContributionPlanSearcher.js
- src/constants.js
Introduces changes requested in https://openimis.atlassian.net/browse/OFS-235
> OFS-235: Add placeholders for Calculation module contributions

- src/components/ContributionPlanBundleSearcher.js
- src/components/ContributionPlanSearcher.js
- src/index.js
Fixes issue no. 1 in https://openimis.atlassian.net/browse/OFS-254
> OFS-254: Apply default validity filter when searching

- src/components/ContributionPlanBundleFilter.js
Fixes issue no. 5 reported in https://openimis.atlassian.net/browse/OFS-254
> OFS-254: Add placeholder for Calculation Rule picker

- src/components/ContributionPlanForm.js
- src/components/ContributionPlanHeadPanel.js
https://openimis.atlassian.net/browse/OFS-278
> OFS-278: Block form submission if calculation param validation fails

- src/components/PaymentPlanHeadPanel.js
- src/constants.js
TICKET: https://openimis.atlassian.net/browse/OPL-23
> OPL-23: refactor contribution calcrule for PaymentPlan

- src/translations/en.json
Ticket:
https://openimis.atlassian.net/browse/OTC-958
Changes:
- changed label for attaching contribution plan
> OTC-958: changed label for attaching contribution plan

- src/actions.js
Ticket: https://openimis.atlassian.net/browse/OP-930
Changes:
- Fixed issue with removed contribution plans.
> OP-930: Removed CP's no longer visible.

- src/components/PaymentPlanFilter.js
Ticket:
https://openimis.atlassian.net/browse/OTC-977
Changes:
- added dependency for date pickers
> OTC-977: added dependency for date pickers

- src/actions.js
- src/components/ContributionPlanBundleHeadPanel.js
- src/components/ContributionPlanHeadPanel.js
- src/components/PaymentPlanForm.js
- src/components/PaymentPlanHeadPanel.js
- src/translations/en.json
This reverts commit 249655dc63d8be66e5f50a9b4a31b437ac1b5c83.
> Revert "OP-1358: Enabling the editing of codes for PP, CP and CPB"

- src/components/ContributionPlanBundleFilter.js
- src/components/ContributionPlanBundleSearcher.js
- src/components/ContributionPlanFilter.js
- src/components/ContributionPlanSearcher.js
- src/components/PaymentPlanFilter.js
- src/components/PaymentPlanSearcher.js
https://openimis.atlassian.net/browse/OP-1366
This PR will add show history option to payment plans, contribution plans, and contribution plan bundles.
It needs: https://github.com/openimis/openimis-be-contribution_plan_py/pull/56
> OP-1366: add shwo history option

- src/components/ContributionPlanBundleFilter.js
- src/components/ContributionPlanBundleSearcher.js
- src/components/ContributionPlanFilter.js
- src/components/ContributionPlanSearcher.js
- src/components/PaymentPlanFilter.js
- src/components/PaymentPlanSearcher.js
MERGING RELEASE branches
Release release/23.04
> MERGING RELEASE branches

- src/components/ContributionPlanBundleFilter.js
- src/components/ContributionPlanFilter.js
- src/components/PaymentPlanFilter.js
- src/translations/en.json
[OTC-1087](https://openimis.atlassian.net/browse/OTC-1087)
Changes:
- The functionality for clearing the search criterias when clicking "Reset" button fixed.
- Implementation of functions to handle ProductPicker change.
- Missing translation key has been added to the Lokalise.
[OTC-1087]: https://openimis.atlassian.net/browse/OTC-1087?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OTC-1087: fix resetting search criteria in contribution plan module

- src/actions.js
- src/components/PaymentPlanForm.js
- src/components/PaymentPlanHeadPanel.js
- src/constants.js
- src/pickers/PaymentPlanTypePicker.js
- src/reducer.js
- src/translations/en.json
https://openimis.atlassian.net/browse/CM-189
This PR adjusts frontend for payment plan to accept benefit plan as a subject of payment.
It requires: https://github.com/openimis/openimis-fe-social_protection_js/pull/35
> CM-189: adjust payment plan frontent to benefit plans

- src/actions.js
Attaching contribution plan into ContributionPlanBundle doesn't work therefore such fix is required.
> CM-322: fixed CPBDetails

- src/pickers/PaymentPlanPicker.js
- src/translations/en.json
https://openimis.atlassian.net/browse/CM-487
> CM-487: initial adjustments

- src/pickers/PaymentPlanPicker.js
https://openimis.atlassian.net/browse/CM-766
> CM-766: fetch payment plans related do benefit plan in picker

- src/components/PaymentPlanHeadPanel.js
TICKET: https://openimis.atlassian.net/browse/CM-776
> CM-776: Make periodicity of the BenefitPlan paymentPlan not mandatory 

- src/components/PaymentPlanHeadPanel.js
- src/dialogs/AdvancedCriteriaDialog.js
- src/dialogs/AdvancedCriteriaRowValue.js
- src/translations/en.json
TICKET: https://openimis.atlassian.net/browse/CM-770
> CM-770: moved payment plan criteria from dialog to form

- src/components/PaymentPlanHeadPanel.js
- src/components/PaymentPlanSearcher.js
- src/translations/en.json
https://openimis.atlassian.net/browse/CM-771
> CM-771: add possibility to disable the payment plan

- src/components/PaymentPlanHeadPanel.js
part of https://openimis.atlassian.net/browse/CM-824
> CM-824: benefit plan picker for all types
